---
language: node_js
sudo: false
dist: trusty
node_js: 'stable'

cache:
  directories:
    - $HOME/.npm

stages:
  - "Tests"
  - name: "Release"
    if: branch = master

env:
  global:
    - JOBS=1

jobs:
  fail_fast: true
  include:
    - stage: "Tests"
    - stage: "Release"
      script: skip
      env: []
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

before_install:
  - npm config set spin false
  - npm install -g codecov
  - npm install -g greenkeeper-lockfile@1
  - npm install -g @commitlint/travis-cli
  - npm --version

install:
  - if [[ $TRAVIS_BRANCH =~ greenkeeper || $TRAVIS_PULL_REQUEST_BRANCH =~ greenkeeper ]]; then npm install; else npm ci; fi

before_script:
  - greenkeeper-lockfile-update

script:
  - commitlint-travis
  - npm run lint:js
  - COVERAGE=true npm run test

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - codecov --file=coverage/lcov.info

